# Generated by Django 4.1.5 on 2023-01-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Receita', models.CharField(max_length=50)),
                ('Ingredientees', models.TextField(max_length=300)),
                ('Preparo', models.CharField(max_length=50)),
                ('Rendimento', models.CharField(max_length=50)),
                ('Categoria', models.CharField(max_length=50)),
                ('Por', models.CharField(max_length=50)),
                ('Modo_preparo', models.TextField(max_length=500)),
            ],
        ),
    ]
