# Generated by Django 4.1.5 on 2023-01-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolos', '0002_receita_date_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='Nome_Receita',
            field=models.CharField(choices=[('NOTICIAS', 'NOTICIAS'), ('BOLETOS', 'BOLETOS'), ('CONSULTAS', 'CONSULTAS'), ('EXAMES', 'EXAMES')], max_length=50),
        ),
    ]
